import './globals.css'


import { Inter } from 'next/font/google'

import 'bootstrap/dist/css/bootstrap.min.css';

import 'bootstrap/dist/css/bootstrap.min.css';
//import 'bootstrap/dist/js/bootstrap.bundle.min';
const inter = Inter({ subsets: ['latin'] })

import Link from 'next/link';
import Header from './header/header';
import Footer from './footer/page';
import Maxim from './Home-banner/page';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
  
    <html lang="en">
      <body className={inter.className}>

      <Header />
      {children}
      <Footer />
      </body>
    </html>
  )
}
